// src/components/button.tsx
import React, { ReactNode, MouseEvent } from "react";
import Svg from "@/components/svg";

interface Props {
  className?: string;
  icon?: boolean;
  flat?: boolean;
  round?: boolean;
  active?: boolean;
  color?: string;
  size?: string;
  load?: boolean;
  children?: ReactNode;
  onClick?: () => void;
}

const Button = (props: Props) => {
  const {
    className = "",
    icon = false,
    flat = false,
    round = false,
    active = false,
    color = "",
    size = "",
    load = false,
    onClick = () => {},
    children
  } = props;

  return (
    <button
      className={`modis-button ${icon ? "modis-button--icon" : ""} ${
        flat ? "modis-button--flat" : ""
      } ${round ? "modis-button--round" : ""}
        ${active ? "modis-button--active" : ""}
        ${color ? `modis-button--${color}` : ""}
        ${size ? `modis-button--${size}` : ""}
        ${className}
        `}
      disabled={load}
      onClick={onClick}
    >
      <div className="modis-container">
        {load ? <Svg name="three-dots" /> : children}
      </div>
    </button>
  );
};

export default Button;

// src/components/button.vue
<template>
  <button class="modis-button" :class="classes" @click="click" :disabled="load">
    <div class="modis-container">
      <m-svg v-if="load" name="three-dots"></m-svg>
      <slot v-else></slot>
    </div>
  </button>
</template>

<script>
export default {
  props: {
    icon: {
      type: Boolean,
      default: false
    },
    flat: {
      type: Boolean,
      default: false
    },
    round: {
      type: Boolean,
      default: false
    },
    active: {
      type: Boolean,
      default: false
    },
    color: {
      type: String,
      default: ""
    },
    size: {
      type: String,
      default: ""
    },
    load: {
      type: Boolean,
      default: false
    }
  },
  computed: {
    classes() {
      return [
        {
          "modis-button--icon": this.icon,
          "modis-button--flat": this.flat,
          "modis-button--round": this.round,
          "modis-button--active": this.active
        },
        this.color ? `modis-button--${this.color}` : "",
        this.size ? `modis-button--${this.size}` : ""
      ];
    }
  },
  methods: {
    click(e) {
      this.$emit("click", e);
    }
  }
};
</script>
