// src/components/form.tsx
import React, { useState, useEffect, useContext } from "react";
import * as AV from "leancloud-storage";
import Svg from "@/components/svg";
import Button from "@/components/button";
import md5 from "blueimp-md5";
import marked from "marked";
import DOMPurify from "dompurify";
import Context from "@/utils/Context";
import { Comment } from "@/components/comment";
import { LeancloudConfig } from "@/index";

const LeancloudCommentObject = AV.Object.extend("Comment");
const ValineCommentObject = AV.Object.extend("Comment");

interface Props {
  inputEl: React.RefObject<HTMLDivElement>;
}

const Form = (props: Props) => {
  const { inputEl } = props;
  const [email, setEmail] = useState("");
  const [nick, setNick] = useState("");
  const [link, setLink] = useState("");
  const [content, setContent] = useState("");
  const [html, setHtml] = useState("");
  const [isPreview, setIsPreviewt] = useState(false);
  const [error, setError] = useState("");
  const [load, setLoad] = useState(false);
  const [timer, setTimer] = useState(0);

  const { config, state, dispath, i18n } = useContext(Context);

  useEffect(() => {
    loadUser();

    return () => {
      clearTimeout(timer);
    };
  }, []);

  useEffect(() => {
    if (isPreview) {
      setHtml(markToHtml());
    }
  }, [isPreview]);

  useEffect(() => {
    if (error) {
      clearTimeout(timer);

      setTimer(
        window.setTimeout(() => {
          setError("");
        }, 3000)
      );
    }
  }, [error]);

  const checkEmail = () => {
    let re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

    if (!re.test(email)) {
      setError(i18n["error.email"]);
      return false;
    }

    return true;
  };
  const checkContent = () => {
    if (content === "") {
      setError(i18n["error.content"]);
      return false;
    }

    return true;
  };
  const checkLink = () => {
    if (link === "") return true;

    if (
      !/^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\(\)\*\+,;=.]+$/.test(
        link
      )
    ) {
      setError(i18n["error.link"]);
      return false;
    }

    return true;
  };
  const markToHtml = () => {
    return DOMPurify.sanitize(marked(content));
  };
  const removeRecipient = () => {
    dispath({
      type: "clearReplt"
    });
  };

  const onSend = async () => {
    if (!(checkEmail() && checkContent() && checkLink())) {
      return;
    }

    setLoad(true);

    try {
      let content = markToHtml();
      let comment: Comment;

      if (config.backend === "leancloud") {
        let commentObject = new LeancloudCommentObject();
        let object = {
          email: email,
          emailMd5: md5(email),
          nick: nick,
          link: link,
          content: content,
          pageId: (config.backendConfig as LeancloudConfig).pageId
        };

        if (state.recipient) {
          Object.assign(object, {
            parentId: state.recipient.objectId,
            rootId: state.recipient.rootId || state.recipient.objectId
          });
        }

        commentObject.set(object);

        let resultObject = await commentObject.save();

        comment = {
          nick: resultObject.get("nick"),
          content: resultObject.get("content"),
          emailMd5: resultObject.get("emailMd5"),
          email: resultObject.get("email"),
          link: resultObject.get("link"),
          updatedAt: resultObject.get("updatedAt"),
          createdAt: resultObject.get("createdAt"),
          children: [],
          objectId: resultObject.get("objectId"),
          rootId: resultObject.get("rootId"),
          parentId: resultObject.get("parentId")
        };
      } else {
        let commentObject = new ValineCommentObject();

        let object = {
          mail: email,
          nick: nick || "Anonymous",
          link: link,
          comment: content,
          url: config.pathnameGenerator()
        };

        if (state.recipient) {
          Object.assign(object, {
            pid: state.recipient.objectId,
            rid: state.recipient.rootId || state.recipient.objectId
          });
        }

        commentObject.set(object);

        let resultObject = await commentObject.save();

        comment = {
          nick: resultObject.get("nick"),
          content: resultObject.get("comment"),
          emailMd5: undefined,
          email: resultObject.get("mail"),
          link: resultObject.get("link"),
          updatedAt: resultObject.get("updatedAt"),
          createdAt: resultObject.get("createdAt"),
          children: [],
          objectId: resultObject.get("objectId"),
          rootId: resultObject.get("rid"),
          parentId: resultObject.get("pid")
        };
      }

      if (state.recipient) {
        state.recipient.children.push(comment);

        dispath({
          type: "updateComments"
        });
      } else {
        dispath({
          type: "addRootComment",
          preload: comment
        });
      }

      resetCommentInput();
      setIsPreviewt(false);
      saveUser();
    } catch (error) {
      setError(error.message);
    } finally {
      setLoad(false);
    }
  };

  const togglePreview = () => {
    setIsPreviewt(!isPreview);
  };
  const resetCommentInput = () => {
    setContent("");
    setHtml("");
  };
  const saveUser = () => {
    localStorage.setItem(
      "modis",
      JSON.stringify({
        email: email,
        nick: nick,
        link: link
      })
    );
  };
  const loadUser = () => {
    let data = localStorage.getItem("modis");

    if (data) {
      let user = JSON.parse(data);

      setEmail(user.email);
      setNick(user.nick);
      setLink(user.link);
    }
  };

  return (
    <div className="modis-form" ref={inputEl}>
      <div className="modis-mine">
        <div className="modis-email">
          <div className="modis-icon">
            <Svg name="email-outline" />
          </div>
          <input
            className="modis-input"
            type="email"
            value={email}
            placeholder={i18n.email}
            onChange={e => {
              setEmail(e.target.value);
            }}
          />
        </div>
        <label className="modis-nick">
          <div className="modis-icon">
            <Svg name="account-circle-outline" />
          </div>
          <input
            className="modis-input"
            type="text"
            value={nick}
            placeholder={i18n.nick}
            onChange={e => {
              setNick(e.target.value);
            }}
          />
        </label>
        <div className="modis-link">
          <div className="modis-icon">
            <Svg name="link" />
          </div>
          <input
            className="modis-input"
            type="text"
            value={link}
            placeholder={i18n.link}
            onChange={e => {
              setLink(e.target.value);
            }}
          />
        </div>
      </div>
      {state.recipient && (
        <div className="modis-recipient">
          <div className="modis-info">
            <span>{state.recipient.nick}</span>
            <Button
              flat
              icon
              color="error"
              size="small"
              onClick={removeRecipient}
            >
              <Svg name="clear" />
            </Button>
          </div>
          <div
            dangerouslySetInnerHTML={{
              __html: state.recipient.content
            }}
            className="modis-content"
          />
        </div>
      )}
      <div className="modis-reply">
        {isPreview ? (
          <div
            className="modis-prep modis-input"
            dangerouslySetInnerHTML={{
              __html: html
            }}
          />
        ) : (
          <textarea
            className="modis-input"
            value={content}
            onChange={e => {
              setContent(e.target.value);
            }}
          />
        )}
      </div>
      <div className="modis-bar">
        <Button
          icon
          flat
          size="small"
          className="modis-iconbtn"
          active={isPreview}
          onClick={togglePreview}
        >
          <Svg name="eye" />
        </Button>
        <Button load={load} onClick={onSend}>
          <Svg name="send" />
        </Button>
      </div>
      {error && (
        <div className="modis-error">
          <Svg name="alert-circle" />
          {error}
        </div>
      )}
    </div>
  );
};

export default Form;

// src/components/form.vue
<template>
  <div class="modis-form">
    <div class="modis-mine">
      <div class="modis-email">
        <div class="modis-icon">
          <m-svg name="email-outline" />
        </div>
        <input
          v-model.lazy="email"
          class="modis-input"
          type="email"
          :placeholder="$_t('email')"
        >
      </div>
      <label class="modis-nick">
        <div class="modis-icon">
          <m-svg name="account-circle-outline" />
        </div>
        <input
          v-model.lazy="nick"
          class="modis-input"
          type="text"
          :placeholder="$_t('nickname')"
        >
      </label>
      <div class="modis-link">
        <div class="modis-icon">
          <m-svg name="link" />
        </div>
        <input
          v-model.lazy="link"
          class="modis-input"
          type="text"
          :placeholder="$_t('link')"
        >
      </div>
    </div>
    <div
      v-if="recipient !== null"
      class="modis-recipient"
    >
      <div class="modis-info">
        <span>
          {{ recipient.comment.nick }}
        </span>
        <m-button
          flat
          icon
          color="error"
          size="small"
          @click="removeRecipient"
        >
          <m-svg name="clear" />
        </m-button>
      </div>
      <div
        v-html="recipient.comment.comment"
        class="modis-content"
      />
    </div>
    <div class="modis-reply">
      <div
        v-if="isPreview"
        v-html="html"
        class="modis-prep modis-input"
      />
      <textarea
        v-else
        v-model.lazy="comment"
        class="modis-input"
      />
    </div>
    <div class="modis-bar">
      <m-button
        icon
        flat
        class="modis-iconbtn"
        @click="isPreview = !isPreview"
        :active="isPreview"
        size="small"
      >
        <m-svg name="eye" />
      </m-button>
      <m-button
        @click="post"
        :load="load"
      >
        <m-svg name="send" />
      </m-button>
    </div>
    <transition name="modis-fade">
      <div
        v-if="error"
        class="modis-error"
      >
        <template>
          <m-svg
            name="alert-circle"
            class="modis-icon"
          />
          {{ error }}
        </template>
      </div>
    </transition>
  </div>
</template>

<script>
import DOMPurify from "dompurify";
import marked from "marked";

import CComment from "@/components/comment.vue";

export default {
  _sI18n: {
    en: {
      email: "E-Mail",
      nickname: "Nickname",
      link: "Link",
      error: {
        email: "Please enter vaild email",
        comment: "Please enter a comment",
        link: "Please enter vaild email"
      }
    },
    "zh-CN": {
      email: "邮箱",
      nickname: "昵称",
      link: "链接",
      error: {
        email: "请输入正确的邮箱",
        comment: "请输入评论内容",
        link: "请输入正确的链接"
      }
    }
  },
  data() {
    return {
      email: "",
      emailHash: "",
      emailError: false,
      nick: "",
      link: "",
      comment: "",
      commentError: false,
      html: "",
      isPreview: false,
      recipient: null,
      error: "",
      load: false,
      timer: null
    };
  },
  watch: {
    isPreview: function(n) {
      if (n) {
        this.html = this.markToHtml();
      }
    },
    error: function(n) {
      if (n) {
        clearTimeout(this.timer);

        this.timer = setTimeout(() => {
          this.error = "";
        }, 3000);
      }
    }
  },
  methods: {
    checkEmail() {
      if (
        !/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(
          this.email
        )
      ) {
        this.error = this.$_t("error.email");
      }
    },
    checkComment() {
      if (this.comment === "") {
        this.error = this.$_t("error.comment");
      }
    },
    checkLink() {
      if (this.link === "") return;

      if (
        !/^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\(\)\*\+,;=.]+$/.test(
          this.link
        )
      ) {
        this.error = this.$_t("error.link");
      }
    },
    generateEmailHash() {
      this.emailHash = this.$_md5(this.email);
    },
    markToHtml() {
      return marked(this.comment, {
        sanitize: true,
        sanitizer: DOMPurify.sanitize
      });
    },
    removeRecipient() {
      this.recipient = null;
    },
    async post() {
      //check
      this.error = "";
      this.checkEmail();
      this.checkComment();
      this.checkLink();

      if (this.error) return;
      this.load = true;

      try {
        let recipient = this.recipient;
        let content = this.markToHtml();

        switch (this.$_config.backend) {
          case "valine":
            let commentObject = new this.$_CommentObject();
            let comment = {};

            let object = {
              mail: this.email,
              nick: this.nick || "Anonymous",
              link: this.link,
              comment: content,
              url: this.$_config.pathnameGenerator()
            };

            if (recipient !== null) {
              Object.assign(object, {
                pid: this.recipient.comment.objectId,
                rid:
                  this.recipient.comment.rid || this.recipient.comment.objectId
              });
            }

            commentObject.set(object);

            let resultObject = await commentObject.save();

            for (
              let index = 0;
              index < this.$_config.attributes.length;
              index++
            ) {
              const attribute = this.$_config.attributes[index];
              comment[attribute] = resultObject.get(attribute);
            }

            if (recipient !== null) {
              if (recipient.comment.children) {
                recipient.comment.children.push(comment);
              } else {
                this.$set(recipient.comment, "children", [comment]);
              }
            } else {
              this.$_EventBus.$emit("post", { comment });
            }

            break;
          case "leancloud":
            {
              let commentObject = new this.$_CommentObject();
              let comment = {};
              let object = {
                email: this.email,
                emailMd5: this.$_md5(this.email),
                nick: this.nick,
                link: this.link,
                comment: content,
                pageId: this.$_config.pageId
              };
              if (recipient !== null) {
                Object.assign(object, {
                  parentId: this.recipient.comment.objectId,
                  rootId:
                    this.recipient.comment.rootId ||
                    this.recipient.comment.objectId
                });
              }
              commentObject.set(object);
              let resultObject = await commentObject.save();
              for (
                let index = 0;
                index < this.$_config.commentAttr.length;
                index++
              ) {
                const attribute = this.$_config.commentAttr[index];
                comment[attribute] = resultObject.get(attribute);
              }
              if (recipient !== null) {
                if (recipient.comment.children) {
                  recipient.comment.children.push(comment);
                } else {
                  this.$set(recipient.comment, "children", [comment]);
                }
              } else {
                this.$_EventBus.$emit("post", { comment });
              }
            }

            break;
          default:
            break;
        }

        this.resetCommentInput();
        this.saveUser();
      } catch (error) {
        this.error = error.message;
      }

      this.load = false;
    },
    preview() {
      this.isPreview = !this.isPreview;
    },
    listenReply(preload) {
      this.$_EventBus.$on("reply", preload => {
        this.recipient = preload.recipient;
      });
    },
    cleanRecipient() {
      this.recipient = null;
    },
    resetCommentInput() {
      this.comment = "";
    },
    saveUser() {
      localStorage.setItem(
        "modis",
        JSON.stringify({
          email: this.email,
          nick: this.nick,
          link: this.link
        })
      );
    },
    loadUser() {
      let data = localStorage.getItem("modis");

      if (data) {
        try {
          let user = JSON.parse(data);

          this.email = user.email;
          this.nick = user.nick;
          this.link = user.link;
        } catch (error) {}
      }
    }
  },
  created: function() {
    this.listenReply();
    this.loadUser();
  },
  beforeDestroy: function() {
    clearTimeout(this.timer);
  }
};
</script>
