// src/components/app.tsx
import React, { useState, useEffect, useReducer, useRef, useMemo } from "react";
import * as AV from "leancloud-storage";
import Button from "@/components/button";
import Svg from "@/components/svg";
import Form from "@/components/form";
import Comment, { Comment as CommentInterface } from "@/components/comment";
import Context from "@/utils/Context";
import { Reducer, InitialState } from "@/utils/Reducer";
import I18n from "@/i18n";

import { Config, LeancloudConfig, ValineConfig } from "@/index";

import arrayToTree from "@/utils/ArrayToTree";

interface Props {
  config: Config;
}

const App = (props: Props) => {
  const { config } = props;
  const [state, dispath] = useReducer(Reducer, InitialState);

  const { comments } = state;
  const [isLoad, setIsLoad] = useState(false);
  const [isLast, setIsLast] = useState(false);

  const inputEl = useRef<HTMLDivElement>(null);

  const i18n = useMemo(() => {
    return I18n[config.locale];
  }, [config]);

  useEffect(() => {
    getComments();
  }, []);

  const themeClass = useMemo(() => {
    return `modis modis--${config.theme}`;
  }, [config]);

  const scrollToInput = () => {
    if (inputEl && inputEl.current) {
      inputEl.current.scrollIntoView({
        behavior: "smooth",
        block: "start"
      });
    }
  };

  const getCommentsLeancloud = async () => {
    let commentAttr = config.backendConfig.commentAttr;
    let queryRoot = new AV.Query("Comment");
    let rootComments;
    let queryTemp = [];
    let childrenComments: AV.Queriable[] = [];

    {
      let l = comments.length;
      if (l) {
        queryRoot.lessThan("createdAt", comments[l - 1].createdAt);
      }
      queryRoot.equalTo(
        "pageId",
        (config.backendConfig as LeancloudConfig).pageId
      );
      queryRoot.doesNotExist("parentId");
      queryRoot.descending("createdAt");
      queryRoot.limit(config.pageSize);
      queryRoot.select(commentAttr);
    }

    try {
      rootComments = await queryRoot.find();
    } catch (error) {
      throw error.code === 101
        ? "Please create Class and make security settings"
        : error;
    }

    for (let index = 0, length = rootComments.length; index < length; index++) {
      const rootComment = rootComments[index];
      let query = new AV.Query("Comment");
      query.equalTo("rootId", rootComment.id);
      query.select(commentAttr);
      queryTemp.push(query);
    }

    if (queryTemp.length === 0) {
      childrenComments = [];
    } else {
      let queryChildren = AV.Query.or(...queryTemp);
      childrenComments = await queryChildren.find();
    }

    {
      let comments = rootComments.concat(childrenComments).map(x => {
        let comment: CommentInterface = {
          nick: x.get("nick") || "Anonymous",
          content: x.get("content"),
          emailMd5: x.get("emailMd5"),
          email: x.get("email"),
          link: x.get("link"),
          updatedAt: x.get("updatedAt"),
          createdAt: x.get("createdAt"),
          children: [],
          objectId: x.get("objectId"),
          rootId: x.get("rootId"),
          parentId: x.get("parentId")
        };

        return comment;
      });

      return comments;
    }
  };

  const getCommentsValine = async () => {
    let commentAttr = (config.backendConfig as ValineConfig).commentAttr;
    let queryRoot = new AV.Query("Comment");
    let rootComments;
    let queryTemp = [];
    let childrenComments: AV.Queriable[] = [];

    {
      let l = comments.length;
      if (l) {
        queryRoot.lessThan("createdAt", comments[l - 1].createdAt);
      }

      queryRoot.equalTo("url", config.pathnameGenerator());
      queryRoot.doesNotExist("rid");
      queryRoot.descending("createdAt");
      queryRoot.limit(config.pageSize);
      queryRoot.select(commentAttr);
    }

    try {
      rootComments = await queryRoot.find();
    } catch (error) {
      throw error.code === 101
        ? "Please create Class and make security settings"
        : error;
    }

    for (let index = 0, length = rootComments.length; index < length; index++) {
      const rootComment = rootComments[index];
      let query = new AV.Query("Comment");
      query.equalTo("rid", rootComment.id);
      query.select(commentAttr);
      queryTemp.push(query);
    }

    if (queryTemp.length === 0) {
      childrenComments = [];
    } else {
      let queryChildren = AV.Query.or(...queryTemp);
      childrenComments = await queryChildren.find();
    }

    {
      let comments = rootComments.concat(childrenComments).map(x => {
        let comment: CommentInterface = {
          nick: x.get("nick"),
          content: x.get("comment"),
          emailMd5: "",
          email: x.get("mail"),
          link: x.get("link"),
          updatedAt: x.get("updatedAt"),
          createdAt: x.get("createdAt"),
          children: [],
          objectId: x.get("objectId"),
          rootId: x.get("rid"),
          parentId: x.get("pid")
        };

        return comment;
      });

      return comments;
    }
  };

  const getComments = async () => {
    if (isLast === true) {
      return;
    }

    setIsLoad(true);

    let comments: CommentInterface[];

    if (config.backend === "leancloud") {
      comments = await getCommentsLeancloud();
    } else {
      comments = await getCommentsValine();
    }

    let tree = arrayToTree(comments, {
      customId: "objectId",
      customParentId: "parentId",
      customChildren: "children"
    });

    dispath({
      type: "getComments",
      preload: tree
    });
    setIsLoad(false);
    setIsLast(tree.length < config.pageSize ? true : false);
  };

  return (
    <div className={themeClass}>
      <Context.Provider value={{ config, state, dispath, i18n }}>
        <Form inputEl={inputEl}></Form>
        <div className="modis-comments">
          {comments.map((comment: CommentInterface) => (
            <Comment
              key={comment[config.backendConfig.commentKey]}
              comment={comment}
              scrollToInput={scrollToInput}
            ></Comment>
          ))}
        </div>
        <div className="modis-app-footer">
          {!isLast && (
            <Button round load={isLoad} onClick={getComments}>
              <Svg name="dots-horizontal" />
            </Button>
          )}
        </div>
      </Context.Provider>
    </div>
  );
};

export default App;

// src/App.vue
<template>
  <div
    class="modis"
    ref="self"
  >
    <c-form
      ref="input"
      :recipient="recipient"
      @cleanRecipient="cleanRecipient"
    />
    <div class="modis-comments">
      <c-comment
        v-for="it in comments"
        :key="it.id"
        :comment="it"
      />
    </div>
    <div
      v-if="error"
      class="modis-app-error"
    >
      <m-svg
        name="alert-circle"
        class="modis-icon"
      />
      {{ error }}
    </div>
    <div class="modis-app-footer">
      <m-button
        v-if="!isLast"
        @click="getComments"
        round
        :load="isLoad"
      >
        <m-svg name="dots-horizontal" />
      </m-button>
    </div>
  </div>
</template>

<script>
import CForm from "@/components/form.vue";
import CComment from "@/components/comment.vue";

const arrayToTree = function(array = [], option = {}) {
  let customId = option.customId,
    customParentId = option.customParentId,
    customChildren = option.customChildren;

  let map = {};
  let tree = [];

  for (const item of array) {
    item[customChildren] = [];
    map[item[customId]] = item;
  }

  for (const id of Object.keys(map)) {
    let item = map[id];
    let parentId = item[customParentId];

    if (
      typeof parentId !== "undefined" &&
      typeof map[parentId] !== "undefined"
    ) {
      map[parentId][customChildren].push(item);
    } else {
      tree.push(item);
    }
  }

  return tree;
};

export default {
  components: {
    CForm,
    CComment
  },
  data() {
    return {
      comments: [],
      isLoad: false,
      isLast: false,
      recipient: null,
      error: ""
    };
  },
  methods: {
    scrollToInput() {
      let input = this.$refs.input.$el;
      input.scrollIntoView({
        behavior: "smooth",
        block: "start"
      });
    },
    async getCommentsValine() {
      let attributes = this.$_config.attributes;

      let queryRoot = new this.$_AV.Query("Comment");

      queryRoot.equalTo("url", this.$_config.pathnameGenerator());
      queryRoot.doesNotExist("rid");
      queryRoot.descending("createdAt");
      queryRoot.limit(this.$_config.pageSize);
      queryRoot.select(attributes);

      {
        let l = this.comments.length;
        if (l) {
          queryRoot.lessThan("createdAt", this.comments[l - 1].createdAt);
        }
      }

      let rootComments;
      try {
        rootComments = await queryRoot.find();
      } catch (error) {
        if (error.code === 101) {
          throw "Please create Class and make security settings";
        }
        return;
      }

      let queryTemp = [];

      for (
        let index = 0, length = rootComments.length;
        index < length;
        index++
      ) {
        const rootComment = rootComments[index];

        let query = new this.$_AV.Query("Comment");
        query.equalTo("rid", rootComment.id);
        query.select(attributes);

        queryTemp.push(query);
      }

      let childrenComments;

      if (queryTemp.length === 0) {
        childrenComments = [];
      } else {
        let queryChildren = this.$_AV.Query.or(...queryTemp);
        childrenComments = await queryChildren.find();
      }

      let comments = rootComments.concat(childrenComments).map(x => {
        let comment = {};

        for (let index = 0; index < attributes.length; index++) {
          const attribute = attributes[index];
          comment[attribute] = x.get(attribute);
        }

        return comment;
      });

      return comments;
    },
    async getCommentsLeancloud() {
      let commentAttr = this.$_config.commentAttr;

      let queryRoot = new this.$_AV.Query("Comment");
      queryRoot.equalTo("pageId", this.$_config.pageId);
      queryRoot.doesNotExist("parentId");
      queryRoot.descending("createdAt");
      queryRoot.limit(this.$_config.pageSize);
      queryRoot.select(commentAttr);

      {
        let l = this.comments.length;
        if (l) {
          queryRoot.lessThan("createdAt", this.comments[l - 1].createdAt);
        }
      }

      let rootComments;
      try {
        rootComments = await queryRoot.find();
      } catch (error) {
        if (error.code === 101) {
          throw "Please create Class and make security settings";
        }
        return;
      }

      let queryTemp = [];

      for (
        let index = 0, length = rootComments.length;
        index < length;
        index++
      ) {
        const rootComment = rootComments[index];

        let query = new this.$_AV.Query("Comment");
        query.equalTo("rootId", rootComment.id);
        query.select(commentAttr);

        queryTemp.push(query);
      }

      let childrenComments;

      if (queryTemp.length === 0) {
        childrenComments = [];
      } else {
        let queryChildren = this.$_AV.Query.or(...queryTemp);
        childrenComments = await queryChildren.find();
      }

      let comments = rootComments.concat(childrenComments).map(x => {
        let comment = {};

        for (let index = 0; index < commentAttr.length; index++) {
          const attribute = commentAttr[index];
          comment[attribute] = x.get(attribute);
        }

        comment.nick = comment.nick || "Anonymous";

        return comment;
      });

      return comments;
    },
    async getComments() {
      if (this.isLast === true) return;

      this.isLoad = true;

      let comments, tree;

      switch (this.$_config.backend) {
        case "valine":
          comments = await this.getCommentsValine();
          tree = arrayToTree(comments, {
            customId: "objectId",
            customParentId: "pid",
            customChildren: "children"
          });
          break;
        case "leancloud":
          comments = await this.getCommentsLeancloud();
          tree = arrayToTree(comments, {
            customId: "objectId",
            customParentId: "parentId",
            customChildren: "children"
          });
          break;
        default:
          break;
      }

      this.comments.push(...tree);
      this.isLoad = false;

      if (tree.length < this.$_config.pageSize) this.isLast = true;
    },
    listenReply() {
      this.$_EventBus.$on("reply", () => {
        this.scrollToInput();
      });
    },
    listenPost() {
      this.$_EventBus.$on("post", preload => {
        this.comments.unshift(preload.comment);
      });
    },
    cleanRecipient() {
      this.recipient = null;
    }
  },
  created: function() {
    this.getComments();
    this.listenReply();
    this.listenPost();
  }
};
</script>
